# Generated by Django 6.0.2 on 2026-02-16 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='catalogue.categorie')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Adamaoua', 'Adamaoua'), ('Centre', 'Centre'), ('Est', 'Est'), ('Extreme-Nord', 'Extreme-Nord'), ('Littoral', 'Littoral'), ('Nord', 'Nord'), ('Nord-Ouest', 'Nord-Ouest'), ('Ouest', 'Ouest'), ('Sud', 'Sud'), ('Sud-Ouest', 'Sud-Ouest')], max_length=32)),
                ('ville', models.CharField(max_length=120)),
                ('quartier', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('region', 'ville', 'quartier'),
                'unique_together': {('region', 'ville', 'quartier')},
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(db_index=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_sequestre', 'En sequestre'), ('vendu', 'Vendu')], default='disponible', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalogue.categorie')),
                ('lieu_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalogue.localisation')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='ProduitAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_origine', models.CharField(choices=[('Adamaoua', 'Adamaoua'), ('Centre', 'Centre'), ('Est', 'Est'), ('Extreme-Nord', 'Extreme-Nord'), ('Littoral', 'Littoral'), ('Nord', 'Nord'), ('Nord-Ouest', 'Nord-Ouest'), ('Ouest', 'Ouest'), ('Sud', 'Sud'), ('Sud-Ouest', 'Sud-Ouest')], max_length=32)),
                ('unite_mesure', models.CharField(max_length=24)),
                ('date_recolte', models.DateField(blank=True, null=True)),
                ('duree_conservation', models.PositiveIntegerField(blank=True, null=True)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produit_agricole', to='catalogue.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitRetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=120)),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('occasion', 'Occasion'), ('reconditionne', 'Reconditionne')], default='neuf', max_length=24)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produit_retail', to='catalogue.produit')),
            ],
        ),
    ]
