# Generated by Django 6.0.2 on 2026-02-19 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='catalogue/produits/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.produit')),
            ],
            options={
                'ordering': ('ordre', 'id'),
            },
        ),
    ]
