# Generated by Django 6.0.2 on 2026-02-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='type_vendeur',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('professionnel', 'Professionnel')], default='particulier', max_length=20),
        ),
    ]
